export const TEXT_MAIL = 'TEXT_MAIL';
export const TEXT_PASSWORD = 'TEXT_PASSWORD';
export const LOGIN_FETCHING = 'LOGIN_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT';
